### ISSUE TITLE
[Bug]Run a local network not working 

### ISSUE THREAD

**Issue by caesarchad** [libra/libra#1480]
# 🐛 Bug

The libra book [https://developers.libra.org/docs/run-local-network](https://developers.libra.org/docs/run-local-network) stated that to start a local test net, just need to 
```
$ cd libra
$ cargo run -p libra_swarm -- -s -n 4
```
but actually, the above code snippet is misleading and not working 
## To reproduce

**Code snippet to reproduce**
```rust
# Your code goes here
# Please make sure it does not require any external dependencies
cd libra
cargo run -p libra_swarm -- -s -n 4
```

**Stack trace/error message**
```
// Paste the output here
package `libra_swarm` is not a member of the workspace
```

## Expected Behavior

libra swarm should start to run. 
## System information

**Please complete the following information:**
- 
- 
-

**Comment by sunrye** [comment]
I meet the same problem

**Comment by sunrye** [comment]
> # 🐛 Bug
> The libra book https://developers.libra.org/docs/run-local-network stated that to start a local test net, just need to
> 
> ```
> $ cd libra
> $ cargo run -p libra_swarm -- -s -n 4
> ```
> 
> but actually, the above code snippet is misleading and not working
> 
> ## To reproduce
> **Code snippet to reproduce**
> 
> ```rust
> # Your code goes here
> # Please make sure it does not require any external dependencies
> cd libra
> cargo run -p libra_swarm -- -s -n 4
> ```
> 
> **Stack trace/error message**
> 
> ```
> // Paste the output here
> package `libra_swarm` is not a member of the workspace
> ```
> 
> ## Expected Behavior
> libra swarm should start to run.
> 
> ## System information
> **Please complete the following information:**
> 
> * 
> * 
> * 
> 
> ## Additional context
> Add any other context about the problem here.

I have resolved this bug, the cmd should be `cargo run -p libra-swarm -- -s`. It's libra-swarm not libra_swarm. I found the Cargo.toml's members have changed the libra_swarm to libra-swarm

**Comment by pdhamdhere** [comment]
@caesarchad Thanks for reporting. This seems like a regression from recent rename changes. cc/ @huitseeker

**Comment by bmwill** [comment]
This was intended and it looks like we still have some documentation that needs to be updated to reflect the change. For context this change was done per #1119

**Comment by sherry-x** [comment]
Create https://github.com/libra/website/pull/104 to update the doc

**Comment by tommyyama2020** [comment]
Unsurprisingly, i met the same issue after upgrading my Mac OS.  

Guys. you think this could be similar case ? 
https://github.com/rust-lang/rustfmt/issues/3643

**Comment by tommyyama2020** [comment]
now i have another issue after latest  testnet upgrade.

target/debug/client --host ac.testnet.libra.org --port 8000 -s ./scripts/cli/consensus_peers.config.toml`
Not able to connect to validator at ac.testnet.libra.org:8000, error InvalidSignature

**Comment by tommyyama2020** [comment]
Above worked on Mac OS 10.15.1. thanks. hope somebody will update the website and close the issue.

**Comment by tommyyama2020** [comment]
I think i am going  to pull request for the latest due to simple document changes.

**Comment by bmwill** [comment]
Closing this because I believe the documentation change was made.
